### ISSUE TITLE
Reset line color at end of check-config script

### ISSUE THREAD

**Issue by z3ntu** [janimo/phablet-porting-scripts#2]
It is kinda annoying if the whole console is green or red after running the script.

**Comment by janimo** [comment]
I agree, there's an old pull request (#1) to set the color to white, but it should instead reset to whatever was there before.

**Comment by z3ntu** [comment]
Yeah, that would actually be better, but white is still better than green/red.

**Comment by janimo** [comment]
Ok, I pulled that one. Thanks for the prod.
